# Generated by Django 3.2.7 on 2021-10-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20211002_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_information',
            name='Branch',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_information',
            name='CGPA',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student_information',
            name='Name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_information',
            name='RollNo',
            field=models.CharField(max_length=30),
        ),
    ]
